services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    stop_grace_period: 1s

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    command: celery -A app.tasks worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    stop_signal: SIGINT
    stop_grace_period: 2s

  flower:
    build:
      context: .
      dockerfile: Dockerfile.celery
    command: celery -A app.tasks flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery_worker
    environment:
      - REDIS_URL=redis://redis:6379/0
    stop_signal: SIGINT
    stop_grace_period: 1s

volumes:
  redis_data:
